apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
  namespace: jenkins
  labels:
    app: kaniko-builder
spec:
  restartPolicy: Always

  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["/bin/sh", "-c", "sleep 100d"]
    volumeMounts:
      - name: shared-workspace
        mountPath: /home/jenkins/agent

  volumes:
  - name: shared-workspace
    hostPath:
      path: /tmp/jenkins-workspace
      type: DirectoryOrCreate