apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # 이 PVC는 jenkins 네임스페이스에 만듭니다.
  name: jenkins-kaniko-shared-workspace
  namespace: jenkins
spec:
  # 대부분의 표준 쿠버네티스 환경에서 동작합니다.
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # 5GB의 공간을 요청합니다.
      storage: 5Gi